### ISSUE TITLE
How to run on USRP RIO 2944R

### ISSUE THREAD

**Issue by oscar879399** [ewine-project/Flexible-GFDM-PHY#5]
Dear,

I can not run this code on my USRP RIO 2944R, can you help me please? i have some interrogants for you about the possible reason that is does not work in my USRP...I am workin in my degree work for bachelor degree ....I need use a transceiver of GFDM and this is the only one.

**Comment by PaulKuehne** [comment]
Dear Oscar879399,

Thank you for your question.
Can you describe in more detail what is the problem? A few screenshots might help us.

**Comment by oscar879399** [comment]
![imagen](https://user-images.githubusercontent.com/40328209/42047801-f834aea8-7ac6-11e8-8bfc-aec6a9616aab.png)
![imagen](https://user-images.githubusercontent.com/40328209/42048638-716338a6-7ac9-11e8-8c49-65af2d6b1d78.png)
Paul, thanks for answer me, I have this error today with the last updated code upload by you. any suggestion maybe?

**Comment by oscar879399** [comment]
I appreciate the option to change the modulation is a great tool for my purposes.

I run the VLC with the UDP ports and the IP configured as is the video: https://www.youtube.com/watch?v=13LcyiDZrC0&feature=youtu.be
I also used my PC IP and the video ports, and I did not have reception from udp in vlc, also compile the bitfiles again because maybe that was the problem, and neither ... I'm using the 30db cable with attenuation that you suggest in the description of the code and I have no results either.

What worries me is that the RX and TXT leds of the USRP never turn on while I see that in the block diagram that is plotting a TX signal.

**Comment by PaulKuehne** [comment]
Hello Oscar,
The errors I see in screenshot above are LabVIEW Comm compiler errors. Such errors can occasionally occur in any project (LabVIEW Comm issue). To clear the error, close LabVIEW, then delete the project compilation files (see Figure 1), then start LabVIEW again and open “GFDM Host.gvi”. Repeat this until it compiles without errors (usually once is enough).
![1](https://user-images.githubusercontent.com/36697313/42079201-518bc8d4-7b7f-11e8-9f29-3251950ef236.png)
I would suggest in the first step try to run Project with default Parameter (without reading UDP). When you are sure that PHY link works, you can try UDP. 
After starting the Host VI, make sure transmitter is working.
Open "TX" tab (left site) and check if TX signal is plotted. Also check that the amplitude of the signal is not too large or too small. You can change the amplitude of the TX signal with the "TX.modem.bitshift_in" parameter (see Figure 2).
![2](https://user-images.githubusercontent.com/36697313/42079233-6cee5452-7b7f-11e8-8a14-d3c1988a019f.png)
In the next step, check if sync works. Go to "Receiver" tab and check if "RX.sync.sync found out" counter is running high.
![3](https://user-images.githubusercontent.com/36697313/42079255-79fcc8ae-7b7f-11e8-9289-64921c77f6e8.png)
After that go back to “Data processing”, check the constellation, and frame error rate. Play with "shift"-parameters to obtain the optimal constellation. 
![4](https://user-images.githubusercontent.com/36697313/42080071-b948bf20-7b81-11e8-81c9-68841ce67fe6.png)

> What worries me is that the RX and TXT leds of the USRP never turn on while I see that in the block diagram that is plotting a TX signal.

To my knowledge, the LEDs should not light up during transmission.


BR

**Comment by PaulKuehne** [comment]
Oscar,

I just tested the latest version on USRP 2944R and it worked for me. Nevertheless, the AGC currently does not work on this USRP-Type, so it may be that signal power is too high when you use a cable.
And another note: if you use UDP, that it is better to disable CRC. CRC block does not produce output when an error is detected.

BR

**Comment by PaulKuehne** [comment]
Dear Oscar,

Please try the new version, where I fixed the bug with Gain-Setting.
Note: RX Gain can be changed adaptively by FPGA, but TX Gain is fixed.
If the power of received signal is too high and the signal is clipped (which you can recognize by the shape of the received preamble), you should reduce the TX Gain (ATR-> init TX Power [dBm]).
Note: to apply the new gain, you have to restart VI 

BR

**Comment by oscar879399** [comment]
Dear Paul,

Much obliged for your help and your patience dedicated to my case, I will reinitiate on Monday because my university does not allow me to use the labs on weekends, I will take into consideration all the tips that you have written to me to be able to perform the respective tests, with your help I am sure I will achieve it.

I will write my results for future users.

About the LEDs, I think I did not express myself correctly, I was referring to these:
I have this doubt, should these LEDs light up when I am using the transceiver without UDP and also when I am using it with UDP?
![image](https://user-images.githubusercontent.com/40328209/42121568-239e428a-7bf7-11e8-83c5-7aae7bc49977.png)
Note: in that image I was not doing anything with the USRP.

Regards,

**Comment by PaulKuehne** [comment]
Dear Oscar,

I think the LEDs should not light up in both cases. Besides, for USRP it makes no difference if UDP is used or not. Host VI reads UDP or generates data itself and sends it to USRP.

In the picture I notice that you use two attenuators. Are they both -30 dB? If so, then you have an overall attenuation of -60 dB. In this case, the signal will arrive very weak. If these are -30 dB attenuators, please use only one attenuator on TX side.
If you use antennas, you do not need an attenuator.

BR

**Comment by oscar879399** [comment]
Dear paul, 
I tested the last version and it works very well, I am so happy since  due to  your help now I can use this great code correctly.

Effectively I were using two attenuators, that was wrong, thanks for your observation, perhaps the main problem that occurred was the original bitfile before of that you uploaded changes because did not works in my version of USRP, USRP-BitfileChEstK64-0023.lvbitx worked on USRP 2944R in the "configure FPGA block" of Host.vi 

Now I know that the gain RX can be adjusted on the USPR of 160 MHz but the TX is fixed.

For the monent I think only I going to transmit bits and ajust the tx signal to a signal with characteriscs and parameters almost like a 5G signal in order to get better speed of data trasmit and next analize the BER and the MER.

Many Thanks for your help!
BR

**Comment by paulgiovallejo** [comment]
Dear Paul, 

I have several questions about the code if you can help me please.

How can we adjust or modify the bandwidth?
We need to determine the BER for that reason, where is the exit and entry signal to get the BER?
We need to modify the frequency to which we are working, where can we modify this parameter?

Thank you very much for your help, I hope you can help me with those questions.
Regards

**Comment by oscar879399** [comment]
Hello Paul,

I ask for your help again please, I have advanced a lot in trying to transmit, at the beginning that was my problem.

Now I have tried to transmit video correctly without errors but I still have not achieved, I captured some screenshots to show all the data I receive and the configuration of each tab to get the best possible reception, however the video does not arrive correctly, either the audio, also I tried to change the number of udp packages with the MTU command in VLC Within a .bat type file

start ""% VLC% --repeat% VIDEO% --mtu = 188: sout = # std {access = udp {ttl = 1}, mux = ts, dst = 127.0.0.1:% UDP_PORT_TX%}

However, it did not work either, is it possible to provide me with the video that you use in the YouTube video? that works very well, theoretically any video should work, but I consider that when using a USRP of 160MHZ I have gain problems in the TX.

I attach the link to the file with the screenshots:

BR

**Comment by oscar879399** [comment]
PD: The constellation diagram is blinking, so in the screenshot it seems that the symbols are not there

**Comment by PaulKuehne** [comment]
Hello oscar879399 and paulgiovallejo,

Thanks for your questions!
Unfortunately, I am out of the office this week and have no access to the project. I'm beginning to answer your questions early next week. Until then, please open new "issue", with appropriate name.
Many Thanks!

Best regards
