### ISSUE TITLE
Video reception with errors on 160 MHz USRP

### ISSUE THREAD

**Issue by oscar879399** [ewine-project/Flexible-GFDM-PHY#6]
Hello Paul,

Firstly thank you for your continue support, some issues about the recepccion have arised with the 160MHz USRP

I have tried to transmit video correctly without errors but I still have not achieved, I made some screenshots to show all the data I receive and the configuration of each tab to get the best possible reception, however the video does not arrive correctly, nor the audio, also I tried with change the number of udp packages with the MTU command in VLC Within a .bat type file

start ""% VLC% --repeat% VIDEO% --mtu = 256 : sout = # std {access = udp {ttl = 1}, mux = ts, dst = 127.0.0.1:% UDP_PORT_TX%}

I changed the values of the MTU from 256 up to 3328 but does not affect in anything.

Is it possible to provide me with the Tutorial video that you use on YouTube? that works very well, theoretically any video should work, but I rackon that when using a USRP of 160MHZ I have gain problems in the TX because I use a RX gain of 31.5 that is the limit.

I tested with 20MHz of bandwidht even 50MHz, and tested with differents values of Time interval transsmisison.

I attach the link to the file with some screenshots:

The constellation diagram is blinking, so in the screenshot it seems that the symbols are not there, is this normal? is not constant, each half second aproximatly have a abrupted distorsion.

Also, I can see on the video on youtube that the video run slowly, just in this time of the video Tutorial:
https://youtu.be/tgz2hZNoKSI?t=603

Could this a reason of I receive my video with many pixels? I need fix to a Time interval transsmisison more long than 20000 or 100000 i tried with the two last values, scaling of 20000 by 20000.

I discarded the possiblity of some interference signal exist trought of run the same video on the LTE framework example of NI at the same frecuency.

BR

**Comment by PaulKuehne** [comment]
Hello oscar879399,

Is the same configuration working if you disable UDP (with data generated on the host)?
The UDP packet length should be equal to "PayloadSize", so 257 bytes for your setting

BR,
Paul
